import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import {ReactNode} from "react";
import Providers from "@/app/redux/provider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(
    {
        children,
    }: {
        children: ReactNode
    }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            <div>
                <Header/>
                <Sidebar/>
            </div>
        </Providers>
        </body>
        </html>
    )
}
